language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"

install:
    - pip install .

script: nosetests --with-coverage --cover-package=confuse

# coveralls.io reporting, using https://github.com/coagulant/coveralls-python
# Only report coverage for one version.
before_script:
    - "[[ $TRAVIS_PYTHON_VERSION == '3.3' ]] && pip install coveralls || true"
after_success:
    - "[[ $TRAVIS_PYTHON_VERSION == '3.3' ]] && coveralls || true"

sudo: false
